minimumReleaseAge: 10080
blockExoticSubdeps: true
trustPolicy: no-downgrade
overrides:
  "chokidar": ">=5.0.0"
  "ua-parser-js": ">=2.0.10"
  "semver": ">=7.5.2"
  "esbuild": ">=0.28.1"
  "lmdb": ">=1.7.4"
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
